#autogenerated by sqlautocode

from sqlalchemy import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relation

engine = create_engine('mysql://haofuadm:yin%2Cbingjun@localhost/haofu')
DeclarativeBase = declarative_base()
metadata = DeclarativeBase.metadata
metadata.bind = engine

class Account(DeclarativeBase):
    __tablename__ = 'account'

    __table_args__ = {}

    #column definitions
    AT = Column(u'AT', TIMESTAMP(), nullable=False)
    DEL = Column(u'DEL', BIT(length=1), nullable=False)
    Email = Column(u'Email', VARCHAR(length=45), nullable=False)
    Id = Column(u'Id', INTEGER(), primary_key=True, nullable=False)
    LMT = Column(u'LMT', TIMESTAMP(), nullable=False)
    Locked = Column(u'Locked', BIT(length=1), nullable=False)
    LoginId = Column(u'LoginId', VARCHAR(length=45), nullable=False)
    Pwd = Column(u'Pwd', VARCHAR(length=45), nullable=False)

    #relation definitions


class Game(DeclarativeBase):
    __tablename__ = 'game'

    __table_args__ = {}

    #column definitions
    AT = Column(u'AT', TIMESTAMP(), nullable=False)
    Code = Column(u'Code', VARCHAR(length=16), nullable=False)
    DEL = Column(u'DEL', BIT(length=1), nullable=False)
    Id = Column(u'Id', INTEGER(), primary_key=True, nullable=False)
    LMT = Column(u'LMT', TIMESTAMP(), nullable=False)
    Name = Column(u'Name', VARCHAR(length=16), nullable=False)

    #relation definitions


class Server(DeclarativeBase):
    __tablename__ = 'server'

    __table_args__ = {}

    #column definitions
    AT = Column(u'AT', TIMESTAMP(), nullable=False)
    Contact = Column(u'Contact', VARCHAR(length=50))
    DEL = Column(u'DEL', BIT(length=1), nullable=False)
    Feature = Column(u'Feature', VARCHAR(length=32), nullable=False)
    GameId = Column(u'GameId', INTEGER(), nullable=False)
    ISP = Column(u'ISP', VARCHAR(length=16), nullable=False)
    Id = Column(u'Id', INTEGER(), primary_key=True, nullable=False)
    LMT = Column(u'LMT', TIMESTAMP(), nullable=False)
    Name = Column(u'Name', VARCHAR(length=16), nullable=False)
    OpenTime = Column(u'OpenTime', DATETIME(), nullable=False)
    Ratio = Column(u'Ratio', VARCHAR(length=16), nullable=False)
    Uri = Column(u'Uri', VARCHAR(length=500), nullable=False)
    Version = Column(u'Version', VARCHAR(length=16), nullable=False)

    #relation definitions


